INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('short-tee', 'TOP', 'TOP', '반팔 티셔츠', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('long-tee', 'TOP', 'TOP', '긴팔 티셔츠', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('shirt', 'TOP', 'TOP', '셔츠', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('blouse', 'TOP', 'TOP', '블라우스', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('sweatshirt', 'TOP', 'TOP', '맨투맨', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('hoodie', 'TOP', 'TOP', '후드티', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('knit', 'TOP', 'TOP', '니트', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('cardigan', 'TOP', 'TOP', '가디건', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('sleeveless', 'TOP', 'TOP', '민소매/나시', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('turtleneck', 'TOP', 'TOP', '폴라티', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('shorts', 'PANTS', 'BOTTOM', '반바지', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('jeans', 'PANTS', 'BOTTOM', '청바지', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('slacks', 'PANTS', 'BOTTOM', '슬랙스', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('cotton-pants', 'PANTS', 'BOTTOM', '면바지', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('leggings', 'PANTS', 'BOTTOM', '레깅스', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('skirt', 'SKIRT', 'BOTTOM', '치마', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('windbreaker', 'OUTER', 'OUTER', '바람막이', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('denim-jacket', 'OUTER', 'OUTER', '청자켓', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('leather-jacket', 'OUTER', 'OUTER', '가죽자켓', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('trench-coat', 'OUTER', 'OUTER', '트렌치코트', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('padding', 'OUTER', 'OUTER', '패딩', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('long-coat', 'OUTER', 'OUTER', '롱코트', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('parka', 'OUTER', 'OUTER', '파카', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('raincoat', 'OUTER', 'OUTER', '레인코트', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('blazer', 'OUTER', 'OUTER', '블레이저', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('mini-dress', 'DRESS', 'DRESS', '미니 원피스', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('midi-dress', 'DRESS', 'DRESS', '미디 원피스', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('long-dress', 'DRESS', 'DRESS', '롱 원피스', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('shirt-dress', 'DRESS', 'DRESS', '셔츠 원피스', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('jumpsuit', 'DRESS', 'DRESS', '점프수트', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('sneakers', 'SHOES', 'SHOES', '운동화', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('loafers', 'SHOES', 'SHOES', '로퍼', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('boots', 'SHOES', 'SHOES', '부츠', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('sandals', 'SHOES', 'SHOES', '샌들', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('slippers', 'SHOES', 'SHOES', '슬리퍼', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('rain-boots', 'SHOES', 'SHOES', '장화', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('heels', 'SHOES', 'SHOES', '힐/구두', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('cap', 'ACCESSORY', 'HAT', '볼캡', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('bucket-hat', 'ACCESSORY', 'HAT', '버킷햇', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('beanie', 'ACCESSORY', 'HAT', '비니', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('beret', 'ACCESSORY', 'HAT', '베레모', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('sun-hat', 'ACCESSORY', 'HAT', '썬햇', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('scarf', 'ACCESSORY', 'SCARF', '스카프', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('muffler', 'ACCESSORY', 'SCARF', '머플러', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('neck-warmer', 'ACCESSORY', 'SCARF', '넥워머', NOW(), NOW());
INSERT INTO `clothing_item` (`system_key`, `category`, `display_group`, `name_ko`, `created_at`, `updated_at`) VALUES ('shawl', 'ACCESSORY', 'SCARF', '숄', NOW(), NOW());
